name: real_estate
description: "A new Flutter project for Real Estate app."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^14.1.4
  get_it: ^7.7.0
  flutter_svg: ^2.0.10+1
  mobx: ^2.3.3+2
  flutter_mobx: ^2.2.1+1
  flutter_staggered_grid_view: ^0.7.0
  google_maps_flutter: ^2.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/json/
    - assets/svg/

  fonts:
    - family: EuclidCircularA
      fonts:
        - asset: assets/fonts/Euclid-Circular-A-Regular.ttf

